extra types
Knawat/knawat-suppliers-npm pull request #44
Opened 2021-03-16 15:14 UTC by cactusaurelius

## :memo: Description

### :dart: Relevant issues

### :gem: Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### :scroll: Example code
```js

``` 

## :vertical_traffic_light: How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## :checkered_flag: Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] **I have added tests that prove my fix is effective or that my feature works**
- [ ] **New and existing unit tests pass locally with my changes**
- [ ] I have commented my code, particularly in hard-to-understand areas

2021-03-18 05:49 UTC, HazemKhaled requested changes
More info please!

2021-03-21 08:22 UTC, cactusaurelius commented
Added types for the unthrottled fetch method to use for async routes

2021-03-21 08:31 UTC, HazemKhaled requested changes
please stay commited to the PR template

![image](https://user-images.githubusercontent.com/125433/111898756-ff3e3280-8a38-11eb-9809-3b0489637927.png)

2021-03-22 07:08 UTC, HazemKhaled approved these changes

2021-03-22 07:09 UTC, merged