use fulfillment auth
Knawat/knawat-suppliers-npm pull request #50
Opened 2021-06-01 04:20 UTC by neer14

## :memo: Description

Fix authorization for BearerFulfillment

2021-06-01 06:23 UTC, HazemKhaled requested changes

2021-06-01 06:23 UTC, HazemKhaled commented on src/lib/request.js
> +      this.headers.authorization = `BearerFulfillment ${fulfillmentToken}`;
no, fix out API to handle prefix instead of changing the keyword bearer
so suppliers consumer key should start with `sup_xxxxx`
fulfillment should start with `ffc_xxxxx`
Don't migrate any suppliers, just migrate fulfillment centers

2021-06-01 09:48 UTC, neer14 commented on src/lib/request.js
> +      this.headers.authorization = `BearerFulfillment ${fulfillmentToken}`;
@HazemKhaled 
can you accept this for now so we can close current fulfillment tasks?

2021-06-03 07:03 UTC, HazemKhaled requested changes

2021-06-03 07:03 UTC, HazemKhaled commented on src/lib/request.js
> +      this.headers.authorization = `BearerFulfillment ${fulfillmentToken}`;
SApp sprint already closed, developers already woking on another tasks now, please finish this when you have time

2021-08-09 20:25 UTC, HazemKhaled requested changes

2021-08-09 20:25 UTC, HazemKhaled commented on src/lib/request.js
> +      this.headers.authorization = (process.env.NODE_ENV === 'production') ? `Bearer ${supplierToken}`:`Bearer sup_${supplierToken}`;
I expect SP return sup_ or ffc_, the user should not add the prefix himself, we should handle it into https://github.com/Knawat/sp/blob/develop/services/auth.service.js#L48

2021-08-12 14:49 UTC, closed without merging