Feature/SP-322-add async endpoints
Knawat/knawat-suppliers-npm pull request #53
Opened 2021-08-27 05:16 UTC by neer14

## :memo: Description

Task: https://app.asana.com/0/800760569056877/1200588877678244
_Set default async for endpoints which don't have `GET` method_
_Enable set_async flag for all functions except `GET` method_

### :gem: Type of change

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

## :checkered_flag: Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] **I have added tests that prove my fix is effective or that my feature works**
- [ ] **New and existing unit tests pass locally with my changes**
- [ ] I have commented my code, particularly in hard-to-understand areas

2021-09-01 09:34 UTC, cactusaurelius approved these changes

2021-09-15 14:19 UTC, cactusaurelius requested changes

2021-09-16 04:11 UTC, neer14 commented on src/lib/request.js
> +      asyncPath = Number(process.env.SET_ASYNC) === 0 || Number(options.SET_ASYNC) === 0 ? '' : '/async';
@cactusaurelius npm should use async by default

2021-09-18 17:48 UTC, HazemKhaled approved these changes

2021-09-18 17:48 UTC, merged